### ISSUE TITLE
Problem installing generated extension

### ISSUE THREAD

**Issue by X-Tender** [misterboe/startpilot#104]
I've ran the curl command which generated the extension in the ./packages/myExtension folder.
I've updated the `repositories` child of the composer.json that it looks like ehat:
```
"repositories": [
		{ "type": "composer", "url": "https://composer.typo3.org/" },
		{
			"type": "path",
			"url": "packages/*/"
		}
	],
```
When i run `composer require myExtension` I get the error:
```
[InvalidArgumentException]
  Could not find package kickstartSlim at any version for your minimum-stabil
  ity (stable). Check the package spelling or your minimum-stability
```

Did I miss something?

**Comment by X-Tender** [comment]
Ok I've installed it by adding it to the composer.json and run `composer update`. However, after I've added the static template and the TSConfig in the resources the plugin didn't seem to be running. The TextImage element (and also when I generate it vie the gen script) isn't visible. I also noticed that it didn't appear in the TS Object Brwoser under the 'plugin' key.

**Comment by X-Tender** [comment]
Ok I found the problem, was a user issue :) Works as intended. However it would be nice that the installation which is described would work via composer require

**Comment by misterboe** [comment]
Hi @X-Tender, i will have a look on that. If you have any problems you also could contact my in the typo3 slack.
