### ISSUE TITLE
Use TYPO3 application context 

### ISSUE THREAD

**Issue by miroolma** [misterboe/startpilot#17]

**Comment by arndmesser** [comment]
Wichtig dazu sind folgende Manuals:

https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Bootstrapping/Index.html#bootstrapping-context

https://docs.typo3.org/typo3cms/extensions/bsdist/Main/ApplicationContext/Index.html

**Comment by misterboe** [comment]
thx to @arndmesser
