### ISSUE TITLE
Install startpilot to package dir

### ISSUE THREAD

**Issue by misterboe** [misterboe/startpilot#47]

**Comment by bmack** [comment]
The docs do not state in which directory the site extension is created, and does not show which. If I chdir to `code/web/typo3conf/ext/` and execute the command, the start.sh script does not work. Can you update README.md to show better what does it do and what is added where? Thanks!

**Comment by arndmesser** [comment]
Is it a good idea to implement a flag like `-d | --directory` to specify a custom installation path?
At the moment it is only `typo3conf/ext/`

**Comment by misterboe** [comment]
The provider ext wil now be places to ./packages/ to use a composer install for the provider ext. Docs must be updated.
