### ISSUE TITLE
cropVariants.[myVariant].title expects a translation key

### ISSUE THREAD

**Issue by arndmesser** [misterboe/startpilot#71]
In TYPO3 9.x the cropVariant title muss be a translation key.
See: https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/ImageManipulation.html?highlight=cropvariants

On line 37 in:
~/typo3/sysext/backend/Resources/Private/Templates/ImageManipulation/ImageManipulationElement.html

`
<b><f:translate id="{cropVariant.title}" default="{cropVariant.title}" /></b><br/>
`

therefore it muss be something like:
`
'title' => 'LLL:EXT:startpilot/Resources/Private/Language/locallang.xlf:imageManipulation.mobile',
`
and not 
`'title' => 'Mobile',`

**Comment by misterboe** [comment]
Core Bug => Closed in master after 9.4
