### ISSUE TITLE
Replace INCLUDE_TYPOSCRIPT with @import

### ISSUE THREAD

**Issue by arndmesser** [misterboe/startpilot#74]
https://docs.typo3.org/typo3cms/CoreApiReference/latest/ApiOverview/TypoScriptSyntax/Syntax/Includes.html

**Comment by arndmesser** [comment]
> For TSconfig code use a directory called TSconfig/, possibly with subdirectories named Page/ for Page TSconfig and User/ for User TSconfig.

Include subdirectories in a file called Page.tsconfig and User.tsconfig

**Comment by misterboe** [comment]
Comes with #83
