### ISSUE TITLE
Add .nvmrc file to Resources/Build

### ISSUE THREAD

**Issue by martin-eberle** [misterboe/startpilot#78]
For example when using Codeship for CI/CD, we're currently installing node with a command like `nvm install v8.11.4` before doing the `npm ci` / `npm install` step. So we need do define a node version in each codeship project, which may after some weeks not anymore be the same we use on our local development machines.

The idea is to place a `.nvmrc` file inside the `Resources/Build/` directory with the desired version and only executing `nvm install` within the CI/CD. So it can be ensured that the same node version is used for CI/CD as was used before on the local development machine. What do you think about this?

But then we need to discuss something else: which node version should we define in the startpilot template? The latest LTS? (currently `v8.11.4`)

**Comment by misterboe** [comment]
These settings should be places in the project root. As we only have a provider extension i think we dont need that in there.

**Comment by martin-eberle** [comment]
But think about that the node version is important to fit the dependencies in the `package.json` file, which is also located inside `Resources/Build/`. So in my opinion that would be the right place for a `.nvmrc` file.
