### ISSUE TITLE
The default shell (/bin/sh) under Ubuntu points to dash, not bash

### ISSUE THREAD

**Issue by arndmesser** [misterboe/startpilot#89]
On ubuntu 18.04

> $ readlink -f $(which sh)                                                                                                               master  
> /bin/dash

Running it with `[...] sh start.sh [...]` will not work because the hashbang line will be ignored and the script will be interpreted by dash, which results in an error output:
> start.sh: 3: start.sh: [[: not found
> start.sh: 1: start.sh: Bad substitution
> start.sh: 35: start.sh: Bad substitution

I will update the readme.md file asap.

**Comment by misterboe** [comment]
Please have a look at the readme

> This script is tested on macOS X.
